language: cpp
sudo: required
os: linux
dist: bionic
branches:
  only:
  - master
compiler:
    - gcc
cache:
    directories:
        - /home/travis/vcpkg/
env:
    - CONFIGURATION=Release
    - CONFIGURATION=Debug
    - PLATFORM=x86
    - PLATFORM=x64

install:
    - sudo apt-get install cmake libsdl2-dev libsdl2-image-dev #libgtest-dev
    - pushd /home/travis
    - git clone https://github.com/Microsoft/vcpkg.git
    - cd vcpkg
    - ./bootstrap-vcpkg.sh
    - ./vcpkg install sdl2 sdl2-image gtest --triplet x64-linux
    - ./vcpkg integrate install
    - popd

before_script:    
    - mkdir out
    - pushd out
    - cmake ..
    - popd
script:
    - cmake -A ${PLATFORM} -DCMAKE_BUILD_TYPE=${CONFIGURATION} -DCMAKE_TOOLCHAIN_FILE=/home/travis/vcpkg/scripts/buildsystems/vcpkg.cmake ..--build out
    - ctest
