language: cpp
sudo: required
dist: bionic
compiler:
    - gcc
os:
    - linux
install:
    #- DEPS_DIR=${TRAVIS_BUILD_DIR}/deps
    #- mkdir ${DEPS_DIR} && cd ${DEPS_DIR}
    #- travis_retry wget --no-check-certificate https://cmake.org/files/v3.8/cmake-3.8.2-Linux-x86_64.tar.gz
    - sudo apt-get install cmake
    - sudo apt-get install libsdl2-dev libsdl2-image-dev libgtest-dev
    - cd /usr/src/gtest
    - sudo cmake CMakeLists.txt
    - sudo make
    - sudo cp *.a /usr/lib
    - cd ${TRAVIS_BUILD_DIR}

before_script:    
    - cd ${TRIVIS_BUILD_DIR} && mkdir build && cd build
    - cmake ..
script:
    - cd ${TRAVIS_BUILD_DIR}
    - cmake --build build
    - ctest
