language: cpp
sudo: required
os: linux
dist: bionic
branches:
  only:
  - master
compiler:
    - gcc
cache:
    directories:
        - /home/travis/vcpkg/

env:
    - CONFIGURATION=Debug
    - CONFIGURATION=Release

install:
    - pushd /home/travis
    - git clone https://github.com/Microsoft/vcpkg.git
    - cd vcpkg
    - ./bootstrap-vcpkg.sh
    - ./vcpkg install sdl2 sdl2-image gtest
    - ./vcpkg integrate install
    - popd

before_script:    
    - mkdir out
    - cd out
    - cmake -DCMAKE_BUILD_TYPE=${CONFIGURATION} -DCMAKE_TOOLCHAIN_FILE=/home/travis/vcpkg/scripts/buildsystems/vcpkg.cmake ..
script:
    - cmake --build .
    - ctest -V
