language: cpp
sudo: required
os: linux
dist: bionic
branches:
  only:
  - master
compiler:
    - gcc
cache:
    directories:
        - /home/travis/vcpkg/
env:
    - CONFIGURATION=Release
    - CONFIGURATION=Debug
    - PLATFORM=m32
    - PLATFORM=m64

install:
    - sudo apt-get upgrade
    - sudo apt-get -y install cmake libsdl2-dev libsdl2-image-dev
    - pushd /home/travis
    - git clone https://github.com/Microsoft/vcpkg.git
    - cd vcpkg
    - ./bootstrap-vcpkg.sh
    - ./vcpkg install sdl2 sdl2-image gtest --triplet ${CONFIGURATION}-linux
    - ./vcpkg integrate install
    - popd

before_script:    
    - mkdir out
    - cd out
    - cmake -DCMAKE_C_FLAGS=-${PLATFORM} -DCMAKE_CXX_FLAGS=-${PLATFORM} -DCMAKE_BUILD_TYPE=${CONFIGURATION} -DCMAKE_TOOLCHAIN_FILE=/home/travis/vcpkg/scripts/buildsystems/vcpkg.cmake ..
script:
    - cmake --build .
    - ctest -V
