language: cpp
sudo: required
os: linux
dist: bionic
branches:
  only:
  - master
compiler:
    - gcc
install:
    #- DEPS_DIR=${TRAVIS_BUILD_DIR}/deps
    #- mkdir ${DEPS_DIR} && cd ${DEPS_DIR}
    #- travis_retry wget --no-check-certificate https://cmake.org/files/v3.8/cmake-3.8.2-Linux-x86_64.tar.gz
    - sudo apt-get install cmake
    - sudo apt-get install libsdl2-dev libsdl2-image-dev libgtest-dev
    - pushd /usr/src/gtest
    - sudo cmake CMakeLists.txt
    - sudo make
    #- sudo cp *.a /usr/lib
    - find / -name  GTestConfig.cmake
    - 
    - sudo make install
    - popd

before_script:    
    - mkdir out
    - pushd out
    - cmake ..
    - popd
script:
    - cmake --build out
    - ctest
