# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
  CONFIGURATION: 'Debug'

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-latest'
  steps:
    - script: echo ${PWD}
      displayName: "current dir"
    - script: |
        git clone https://github.com/Microsoft/vcpkg.git
        cd vcpkg
        ./bootstrap-vcpkg.sh
        ./vcpkg install sdl2 sdl2-image gtest
        ./vcpkg integrate install
        cd ..
        mkdir build
        cd build
    - script: ninja --version || echo "not found"
      displayName: "check Ninja"

    - script: echo ${PWD}
      displayName: "check curent dir"
    - task: CMake@1
      inputs:
        cmakeArgs: '-DCMAKE_BUILD_TYPE=${CONFIGURATION} -DCMAKE_TOOLCHAIN_FILE=/home/vsts/work/1/s
/vcpkg/scripts/buildsystems/vcpkg.cmake ..'
      displayName: "Cmake task"
